apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  labels:
    app: prometheus
  namespace: monitoring
data:
  prometheus.yaml: |
    global:
      scrape_interval: 5s
      
    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']
---
apiVersion: v1
kind: Service
metadata:
  name: proemtheus
  labels:
    app: prometheus
  namespace: monitoring
spec:
  ports:
    - port: 9090
  clusterIP: None
  selector:
    app: prometheus
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-external
  namespace: monitoring
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
  labels:
    app: prometheus
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 9090
  selector:
    statefulset.kubernetes.io/pod-name: prometheus-0
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: prometheus
  labels:
    app: prometheus
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: prometheus
  serviceName: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      securityContext:
        fsGroup: 2000
      containers:
        - name: prometheus
          image: quay.io/prometheus/prometheus
          args:
            - --config.file=/etc/prometheus/prometheus.yaml
            - --storage.tsdb.path=/data
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: prometheus-config
              mountPath: /etc/prometheus
            - name: prometheus-data
              mountPath: /data
      volumes:
        - name: prometheus-config
          configMap:
            name: prometheus-config
  volumeClaimTemplates:
    - metadata:
        name: prometheus-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
