apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx
data:
  nginx.conf: |
    user nginx;
    worker_processes 1;
    events {
      worker_connections  1024;
    }
    http {
      server {
        listen  80;
        server_name localhost;
        rewrite ^/(.*)/$ /$1 permanent;

        location /metrics {
          default_type "text/plain";
          alias /usr/share/nginx/html/metrics.txt;
        }
      }
    }
  metrics.txt: |
    requests_total 1234
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
    - image: nginx
      name: nginx
      ports:
        - containerPort: 80
      volumeMounts:
        - mountPath: /etc/nginx
          name: nginx-conf
        - mountPath: /usr/share/nginx/html
          name: metrics
      resources:
        limits:
          memory: 512Mi
          cpu: 1
        requests:
          memory: 128Mi
          cpu: 0.2
  volumes:
    - name: nginx-conf
      configMap:
        name: nginx
        items:
          - key: nginx.conf
            path: nginx.conf
    - name: metrics
      configMap:
        name: nginx
        items:
          - key: metrics.txt
            path: metrics.txt
