apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  labels:
    app: prometheus
  namespace: monitoring
data:
  prometheus.yaml: |
    global:
      scrape_interval: 5s

    scrape_configs:
    - job_name: 'kubernetes-services'
      kubernetes_sd_configs:
      - role: service
        namespaces:
          names:
          - default
      relabel_configs:
      - source_labels: [__meta_kubernetes_service_name]
        regex: kubernetes
        action: drop
    - job_name: 'kubernetes-pods'
      kubernetes_sd_configs:
      - role: pod
      relabel_configs:
      - source_labels: [__meta_kubernetes_pod_name]
        action: replace
        target_label: pod
      # - source_labels: [pod]
      #   regex: ^ebs.*
      #   action: drop
    - job_name: 'kubernetes-endpoints'
      kubernetes_sd_configs:
      - role: endpoints
        namespaces:
          names:
            - default
      relabel_configs:
      - source_labels: [__meta_kubernetes_endpoints_name]
        regex: kubernetes
        action: drop
      - source_labels: [__meta_kubernetes_service_name]
        action: replace
        target_label: service
