apiVersion: v1
kind: Service
metadata:
  name: flask
  labels:
    app: flask
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "80"
spec:
  ports:
    - port: 80
  selector:
    app: flask