apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring
  labels:
    app: prometheus
data:
  prometheus.yaml: |
    global:
      scrape_interval: 5s

    scrape_configs:
    - job_name: 'kubernetes-services'
      kubernetes_sd_configs:
        - role: service
          namespaces:
            names:
              - default
